# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#           1, 2, 3, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whos values do not exceed four million,
# find the sum of the even-valued terms.

calculated = [1,2]

while(True):
    next = calculated[-1] + calculated[-2]
    if next < 4000000:
        calculated.append(next)
    else:
        break

even_sum = 0

for i in calculated:
    if i % 2 == 0:
            even_sum += i

print even_sum
